server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
        - AddRequestHeader=Authorization, #{request.headers.Authorization}
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: grievance-service
          uri: lb://GRIEVANCE-SERVICE
          predicates:
            - Path=/api/v1/grievances/**