server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db_grievance?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Nike2004$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "THIS_IS_A_TEMP_SECRET_CHANGE_IT_LATER_32CHARS"
  expiration: 86400000